export { default as accountSetupApi } from './setup'
export * from './setup'
export { default as userApi } from './user'
export * from './user'
export { default as schoolApi } from './schoolApi'
export * from './schoolApi'